// Drizzle-ORM database client (Postgres via postgres.js).
//
// The exported `db` is a thin Proxy that lazily resolves the real
// Drizzle instance on first property access. This shape lets tests
// inject an alternative driver (e.g. pg-mem-backed) via setDbForTests
// before any DB call happens, without forcing every callsite to
// resolve the connection through a function.
//
// Connection: postgres.js opens a pool against DATABASE_URL. In Next.js
// dev (with HMR module reload) we cache the resolved instance on
// globalThis so reloads don't churn through connection limits. In
// production each function invocation gets its own pool but
// postgres.js + Neon's pooler handle the connection count.
//
// Migrations live in `./drizzle/` (generated by drizzle-kit from
// lib/schema.ts). Apply them with `npm run db:migrate`.

import postgres from "postgres";
import { drizzle, type PostgresJsDatabase } from "drizzle-orm/postgres-js";
import * as schema from "./schema";

type DrizzleDb = PostgresJsDatabase<typeof schema>;

const globalForDb = globalThis as unknown as {
  __hablaDbClient?: ReturnType<typeof postgres>;
  __hablaDrizzle?: DrizzleDb;
};

function makeProductionDb(): DrizzleDb {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error(
      "DATABASE_URL not set. Add it to .env.local for local dev / Vercel env vars for deploy.",
    );
  }
  const client = postgres(url, { prepare: false, max: 10 });
  if (process.env.NODE_ENV !== "production") globalForDb.__hablaDbClient = client;
  return drizzle(client, { schema });
}

function resolveDb(): DrizzleDb {
  if (globalForDb.__hablaDrizzle) return globalForDb.__hablaDrizzle;
  const created = makeProductionDb();
  if (process.env.NODE_ENV !== "production") globalForDb.__hablaDrizzle = created;
  return created;
}

/** Tests inject a pg-mem-backed (or other) Drizzle instance here BEFORE
 *  any lib function runs a query. Production code never calls this. */
export function setDbForTests(testDb: DrizzleDb): void {
  globalForDb.__hablaDrizzle = testDb;
}

// Lazy Proxy: every `db.select(...)`, `db.transaction(...)` etc. dispatches
// through resolveDb() on access. The first access boots the real
// connection (or returns the test override). Cheap — single lookup
// after the first call.
export const db: DrizzleDb = new Proxy({} as DrizzleDb, {
  get(_target, prop, receiver) {
    const real = resolveDb();
    const value = Reflect.get(real as object, prop, receiver);
    return typeof value === "function" ? value.bind(real) : value;
  },
});
