// Drizzle-ORM database client (Postgres via postgres.js).
//
// Replaces the previous better-sqlite3 sync client. Every DB-touching
// callsite now uses the exported `db` instance with async/await:
//
//   import { db } from "./db";
//   import { users } from "./schema";
//   import { eq } from "drizzle-orm";
//
//   const rows = await db.select().from(users).where(eq(users.id, id));
//
// Connection: postgres.js opens a pool against DATABASE_URL. In Next.js
// dev (with HMR module reload) we cache the pool on globalThis so
// reloads don't churn through connection limits. In Vercel production
// each function invocation gets its own pool but postgres.js + Neon's
// pooler handle the connection count.
//
// Migrations live in `./drizzle/` (generated by drizzle-kit from
// lib/schema.ts). Apply them with `npm run db:migrate`.

import postgres from "postgres";
import { drizzle, type PostgresJsDatabase } from "drizzle-orm/postgres-js";
import * as schema from "./schema";

const globalForDb = globalThis as unknown as {
  __hablaDbClient?: ReturnType<typeof postgres>;
  __hablaDrizzle?: PostgresJsDatabase<typeof schema>;
};

function makeClient(): ReturnType<typeof postgres> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL not set. Add it to .env.local for local dev / Vercel env vars for deploy.");
  }
  // postgres.js options:
  //   prepare: false  — Neon's pooler does not support extended-query
  //                     prepared statements with named binding; disabling
  //                     forces simple-query mode which works through pooler.
  //   max: 10         — modest pool, plenty for solo / small-team dev.
  return postgres(url, { prepare: false, max: 10 });
}

const client = globalForDb.__hablaDbClient ?? makeClient();
if (process.env.NODE_ENV !== "production") globalForDb.__hablaDbClient = client;

export const db: PostgresJsDatabase<typeof schema> =
  globalForDb.__hablaDrizzle ?? drizzle(client, { schema });
if (process.env.NODE_ENV !== "production") globalForDb.__hablaDrizzle = db;
